/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SER;
import java.awt.Color;

/**
 *
 * @author Luis Lascano
 */
public class CambiarColor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CambiarColor
     */
    public CambiarColor() {
        initComponents();
        this.setMaximizable(true);
        
        

this.setClosable(true);
this.setIconifiable(true);
       negro.setForeground(Color.black);
       verde.setForeground(Color.green);
       azul.setForeground(Color.blue);
       rojo.setForeground(Color.red);
        defabrica.setForeground(Color.lightGray);
       Color color = this.getBackground();
       System.out.println(color);
        this.getContentPane().setBackground(Color.lightGray);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        rojo = new javax.swing.JRadioButton();
        verde = new javax.swing.JRadioButton();
        negro = new javax.swing.JRadioButton();
        defabrica = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        azul = new javax.swing.JRadioButton();

        buttonGroup1.add(rojo);
        rojo.setText("Rojo");
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });

        buttonGroup1.add(verde);
        verde.setText("Verde");
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });

        buttonGroup1.add(negro);
        negro.setText("Negro");
        negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroActionPerformed(evt);
            }
        });

        buttonGroup1.add(defabrica);
        defabrica.setText("Default");
        defabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defabricaActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un color de fondo:");

        buttonGroup1.add(azul);
        azul.setText("Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defabrica)
                            .addComponent(negro)
                            .addComponent(verde)
                            .addComponent(rojo)
                            .addComponent(azul)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rojo)
                .addGap(18, 18, 18)
                .addComponent(verde)
                .addGap(18, 18, 18)
                .addComponent(negro)
                .addGap(18, 18, 18)
                .addComponent(azul)
                .addGap(18, 18, 18)
                .addComponent(defabrica)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoActionPerformed
       this.getContentPane().setBackground(Color.red);
       
     
       
    }//GEN-LAST:event_rojoActionPerformed

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeActionPerformed
       this.getContentPane().setBackground(Color.green);
    }//GEN-LAST:event_verdeActionPerformed

    private void negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroActionPerformed
       this.getContentPane().setBackground(Color.black);
       
       
       
       
    }//GEN-LAST:event_negroActionPerformed

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulActionPerformed
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_azulActionPerformed

    private void defabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defabricaActionPerformed
       this.getContentPane().setBackground(Color.lightGray);
    }//GEN-LAST:event_defabricaActionPerformed


   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton azul;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton defabrica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton negro;
    private javax.swing.JRadioButton rojo;
    private javax.swing.JRadioButton verde;
    // End of variables declaration//GEN-END:variables


 

}

